name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - name: Build and Deploy
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/deploy.sh
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
